# -*- coding: utf-8 -*-
"""assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gTbG1clPJQ2CdWrgdKha5R98J8h_cIGX
"""

import streamlit as st
import pandas as pd
import datetime

# --- CONFIGURATION ---
st.set_page_config(page_title="My Personal Assistant", layout="wide", page_icon="👤")

# --- DATA LOADING ---
def load_data():
    try:
        # Loading your daily routine (no dates) and your vault
        routine = pd.read_csv('dailyroutine.csv')
        vault = pd.read_csv('personal detail.csv')
        return routine, vault
    except FileNotFoundError as e:
        st.error(f"File not found: {e.filename}. Please check your GitHub files.")
        return None, None

# --- MAIN APP ---
def main():
    st.title("Hi Saksham")

    # Show current time for quick reference
    now = datetime.datetime.now().strftime("%H:%M")
    st.write(f"**Current Time:** {now}")

    routine, vault = load_data()

    if routine is not None and vault is not None:
        # Create Navigation Tabs for Mobile
        tab1, tab2, tab3 = st.tabs(["Daily Routine", "Your Details", "🔍 "])

        with tab1:
    st.header("My Every Day Tasks")
    
    # 1. Convert the 'Time' column to actual datetime objects
    routine['Time'] = pd.to_datetime(routine['Time'], format='%H:%M').dt.time
    
    # 2. Now sort it (8:00 will now correctly come before 10:15)
    routine_sorted = routine.sort_values(by='Time')
    
    # 3. Display the properly ordered table
    st.table(routine_sorted)

        with tab2:
            st.header("Personal Data Vault")

            # Filter by 'Type' (ID, Link, Medical, etc.)
            types = ["All"] + sorted(vault['Type'].unique().tolist())
            selected_type = st.selectbox("Filter by Category", types)

            if selected_type == "All":
                st.table(vault)
            else:
                filtered_vault = vault[vault['Type'] == selected_type]
                st.table(filtered_vault)

        with tab3:
            st.header("Smart Search")
            query = st.text_input("Find anything in your vault...", placeholder="e.g., WiFi, Gym, Blood Group")

            if query:
                # Search logic across the Label and Detail columns
                search_results = vault[vault.apply(lambda row: query.lower() in row.astype(str).str.lower().values, axis=1)]

                if not search_results.empty:
                    st.success(f"Found {len(search_results)} match(es):")
                    st.table(search_results)
                else:
                    st.warning("No information found for that search.")

if __name__ == "__main__":
    main()
